{{- if .Values.cronjob.trigger }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm.fullname" . }}-triggered
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  template:
    spec:
      restartPolicy: {{ .Values.cronjob.restartPolicy }}
      containers:
      - name: nova-find-helm-info
        image: "{{ .Values.cronjob.image.repository }}:{{ .Values.cronjob.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.cronjob.image.pullPolicy }}
        volumeMounts:
        - name: kubeconfig
          mountPath: "/root/.kube"
          readOnly: true
      volumes:
      - name: kubeconfig
        secret: 
          secretName: {{ .Release.Name }}-kubeconfig
{{- end }}