apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-find-helm-info
  namespace: helm-deprecated
spec:
  schedule: "12 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: nova-find-helm-info
            image: ghcr.io/leraymy/helm-deprecated-exporter-conf:v0.0.1
            imagePullPolicy: Always
            volumeMounts:
            - name: kubeconfig
              mountPath: "/root/.kube"
              readOnly: true
          volumes:
          - name: kubeconfig
            secret: 
              secretName: kubeconfig
