apiVersion: batch/v1
kind: CronJob
metadata:
  name: nova-find-helm-info
spec:
  schedule: "0 0 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: nova-find-helm-info
            image: nova-kubectl:0.0.1
            imagePullPolicy: Always
            volumeMounts:
            - name: kubeconfig
              mountPath: "/root/.kube"
              readOnly: true
          volumes:
          - name: kubeconfig
            secret: 
              secretName: kubeconfig
