{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: helm-deprecated-exporter-alertmanager-rules
  {{- if .Values.prometheusRule.namespace }}
  namespace: {{ .Values.prometheusRule.namespace }}
  {{- end }}
spec:
  groups:
    - name: helm-deprecated-rules.rules
      rules:
        - alert: HelmDeprecated
          annotations:
            description: >-
              Helm {{ "{{ $labels.chart_name }}" }} is deprecated, current version is {{ "{{ $labels.installed_version }}" }} and latest is {{ "{{$labels.latest_version}}" }}
            summary: Helm application is deprecated
          expr: >-
            helm_deprecated == 1
          for: 1m
          labels:
            severity: warning
        - alert: HelmOutdated
          annotations:
            description: >-
              Helm {{ "{{ $labels.chart_name }}" }} is outdated, current version is {{ "{{ $labels.installed_version }}" }} and latest is {{ "{{$labels.latest_version}}" }}
            summary: Helm application is outdated
          expr: >-
            helm_outdated == 1
          for: 1m
          labels:
            severity: warning
{{- end }}