apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-kubeconfig
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  config: {{ required "A valid .Values.secret.kubeconfig entry is required!" .Values.secret.kubeconfig }}
